### ISSUE TITLE
Hi! Sincerely invite you to maintain project CampusDailyAutoSign

### ISSUE THREAD

**Issue by yyyanbj** [OdinZhang/HaiNanU_Spider#1]
Hi 👋 ! 目前我们在做的项目[CampusDailyAutoSign](https://github.com/QIN2DIM/CampusDailyAutoSign)，和您的项目有着共同的目的和功能，诚恳的邀请您一同维护!
Email: [beiyuouo@foxmail.com](mailto:beiyuouo@foxmail.com)

**Comment by AustinZhang1024** [comment]
我倒是很愿意参与进来，但是现在大三了，还要忙着准备考研的东西，恐怕精力跟不上，不会太多关注这块的东西，考研结束之后倒是可以慢慢维护这块

**Comment by yyyanbj** [comment]
ok~我们也都是大三哈哈哈哈哈
